### ISSUE TITLE
Hide shipment IDs from page URLs

### ISSUE THREAD

**Issue by finnstue** [Aid-Pioneers/shipment-tracker#65]
**Is your feature request related to a problem? Please describe.**
Currently updating the location of a shipment works like this (works the same for pallets): Scanning the QR code redirects to an URL like /shipments/shipment_id/scans/new. With this, a user could manually update the location of shipments manually without needing to scan the QR code, as the shipment_id is just 1, 2, 3, etc. To prevent location spoofing, we need to obfuscate the url / add random elements to the /scans/new url.

Hiding the shipment_id is only needed on the /shipments/shipments_id/scans/new page URL, as this is the only page that users can visit without needing to login.

**Describe the solution you'd like**
We can use a ruby gem: https://mtm.dev/obfuscate-rails-id

**Describe alternatives you've considered**
This could also work: https://github.com/namick/obfuscate_id.

**Comment by finnstue** [comment]
Okay nice. I have no preference really. Which do you prefer? UUIDs might be easier?

**Comment by killerdaisies** [comment]
@nenko-tabakov  is picking up this ticket. So Basia @nenko-tabakov  and I took a call today and decided on just adding an additional column to give each shipment an EXID (external id) so we're not exposing the actual shipment IDs on the page. Are yall happy with this? @finnstue  @dumboluzz  Nenko will start working on it first, feel free to raise anything!
