### ISSUE TITLE
Enable users to add projects

### ISSUE THREAD

**Issue by finnstue** [Aid-Pioneers/shipment-tracker#67]
**Is your feature request related to a problem? Please describe.**
Currently all shipments in the database belong to one project (Project Ukraine). As Aid Pioneers also has projects in other regions, e.g. Sierra Leone, we need to add a way for users to add projects. Probably, only admin users should be able to add new projects (this is up to debate). The projects in the screenshot below are hardcoded.

**Additional context**
<img width="1552" alt="Projects" src="https://user-images.githubusercontent.com/70270117/179961153-d24c994f-16a0-4f01-9259-e7f904ebf9ba.png">

**Comment by dumboluzz** [comment]
If only admins were to to add projects then the admin panel may be enough.

**Comment by finnstue** [comment]
Yes, agree.

**Comment by nenko-tabakov** [comment]
Where do you think the button to create new project should be?
