### ISSUE TITLE
Add conditions for shipment status

### ISSUE THREAD

**Issue by finnstue** [Aid-Pioneers/shipment-tracker#72]
**Is your feature request related to a problem? Please describe.**
Currently the status of the shipment is input manually when creating the shipment. We need to enable a change in the shipment status based on conditions, eg. shipments still in progress after expected delivery date might have their status changed to problematic. What conditions we need for this is not 100% clear, we might need to discuss this.

**Comment by dumboluzz** [comment]
Should there still be a way to manually set the status of a shipment?

**Comment by finnstue** [comment]
Yes
